# Generated by Django 5.0.6 on 2024-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Comment mezmunu'),
        ),
    ]
